### ISSUE TITLE
Sprachansage

### ISSUE THREAD

**Issue by MarinaFromme** [zwanzigeins/zwanzigeins-app#10]
Die Aussprache der Zahl sollte etwas langsamer erfolgen und eventuell auch differenzierbar sein, sodass die Kinder das "zig" besser heraushören können. Also zwanzig(PAUSE)eins und auch ein(PAUSE)und(PAUSE)zwanzig. So können die Wortbestandteile besser interpretiert werden.

Ein Button bei dem erneut vorgelesen wird, wäre auch hilfreich.

**Comment by lglowania** [comment]
Hallo @MarinaFromme, vielen Dank, dass Sie beitragen!

Die Vorlese-Geschwindigkeit ist jetzt in den Einstellungen einstellbar und der Standard-Wert ist etwas niedriger gesetzt.

Ich nehme an, dass eine langsame Sprechgeschwindigkeit vorerst den Zweck erfüllt. Bei Bedarf könnten wir eine _Differenzierung_ bei Zeiten in einem neuen Issue behandeln.

Das _erneut vorlesen_ kann man durch den Play-Button erreichen.

Ich schließe die Issues, wenn ich glaube, dass die Anfordungen größtenteils erfüllt sind. Falls nicht, können Sie diese aber einfach wieder aufmachen.
