### ISSUE TITLE
Möglichkeiten der Eingabe bei „Stelligkeit“ (Zahlenbereich) begrenzen

### ISSUE THREAD

**Issue by morfep78** [zwanzigeins/zwanzigeins-app#16]
Es können ungültige Zahlenkombinationen eingegeben werden, d.h. bei „von“ kann eine kleinere Zahl als bei „bis“ eingetippt werden. Das verwirrt und führt z.B. bei der Division zu ungewollten Aufgabenstellungen. So kommt es bei der Einstellung für Zahl 1 von 34 bis 33 und für Zahl 2 von 10 bis 15 z.B. zur Aufgabenstellung 34:2.

**Comment by lglowania** [comment]
"von" kann jetzt nicht mehr größer gleich "bis" eingestellt werden und

"bis" kann jetzt nicht mehr kleiner gleich "von" eingestellt werden.

Außerdem können in diese Einstellungen vorerst keine negativen Zahlen mehr eingegeben werden.

**Comment by morfep78** [comment]
Klasse!Petersent from my mobile-------- Originalnachricht --------Betreff: Re: [zwanzigeins/zwanzigeins-app] Möglichkeiten der Eingabe bei „Stelligkeit“ (Zahlenbereich) begrenzen (#16)Von: lglowania An: zwanzigeins/zwanzigeins-app Cc: morfep78 ,Author "von" kann jetzt nicht mehr größer gleich "bis" eingestellt werden und

"bis" kann jetzt nicht mehr kleiner gleich "von" eingestellt werden.

Außerdem können in diese Einstellungen vorerst keine negativen Zahlen mehr eingegeben werden.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/zwanzigeins/zwanzigeins-app/issues/16?email_source=notifications\u0026email_token=ANBURLBRIIA6ZND6PP5QU43Q6HEZVA5CNFSM4KHXBMN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJIAXCA#issuecomment-575671176",

"url": "https://github.com/zwanzigeins/zwanzigeins-app/issues/16?email_source=notifications\u0026email_token=ANBURLBRIIA6ZND6PP5QU43Q6HEZVA5CNFSM4KHXBMN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJIAXCA#issuecomment-575671176",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
