### ISSUE TITLE
Einstellungen bei „Kopfrechen-Trainer“: 

### ISSUE THREAD

**Issue by morfep78** [zwanzigeins/zwanzigeins-app#19]
Es gibt es die Möglichkeit in den Vollbildmodus zu wechseln. Bei Aktivierung des Vollbildmodus wird als kurzfristige Hilfe eingeblendet, dass man von oben ziehen und dann auf die Zurück-Taste tippen soll, um zum Menü zurückzukehren. Das gilt natürlich nur auf bestimmten Smartphones. Auf anderen ist die Zurück-Taste immer dargestellt.

**Comment by lglowania** [comment]
Diesen Hinweis blendet der jeweilige Browser ein, da haben wir keinen Einfluss drauf. Möglicherweise funktioniert auch der Vollbild-Modus nicht überall, dann dürfte diese Option keine Auswirkung haben.

**Comment by morfep78** [comment]
War auch nur eine AnmerkungLGPetersent from my mobile-------- Originalnachricht --------Betreff: Re: [zwanzigeins/zwanzigeins-app] Einstellungen bei „Kopfrechen-Trainer“:  (#19)Von: lglowania An: zwanzigeins/zwanzigeins-app Cc: morfep78 ,Author Diesen Hinweis blendet der jeweilige Browser ein, da haben wir keinen Einfluss drauf. Möglicherweise funktioniert auch der Vollbild-Modus nicht überall, dann dürfte diese Option keine Auswirkung haben.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/zwanzigeins/zwanzigeins-app/issues/19?email_source=notifications\u0026email_token=ANBURLG2UJ6JAOKO2NZV5MDQ6HFNXA5CNFSM4KHXD6Y2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJIBIXA#issuecomment-575673436",

"url": "https://github.com/zwanzigeins/zwanzigeins-app/issues/19?email_source=notifications\u0026email_token=ANBURLG2UJ6JAOKO2NZV5MDQ6HFNXA5CNFSM4KHXD6Y2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJIBIXA#issuecomment-575673436",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
