### ISSUE TITLE
Endnull

### ISSUE THREAD

**Issue by morfep78** [zwanzigeins/zwanzigeins-app#2]
Einstellungen: Optional bei glatten Zehnern die Endnull mitsprechen lassen. Beispiel: 50 nicht als fünfzig sondern als fünzignull sprechen lassen.

**Comment by morfep78** [comment]
Sorry, habe ich beim Rumprobieren versehentlich geschlossen und weil es dann verschwunden war, als Issue4 noch einmal eingegeben

**Comment by MarinaFromme** [comment]
Das halte ich für bedenklich. Wäre nicht fünfzig-null leicht mit 500 zu verwechseln? Zumal bei glatten Zehnern meines Erachtens die wenigsten Schwierigkeiten bei Kindern zu beobachten sind.

**Comment by morfep78** [comment]
Erfolgreich umgesetzt
