### ISSUE TITLE
"Hören und Schreiben" Ergebnisverzerrung durch einstellige Zahlen

### ISSUE THREAD

**Issue by dStephH** [zwanzigeins/zwanzigeins-app#23]
Ich habe beim ersten Testen (2x Zehneins, 2x traditionell). Dabei bin ich auf eine starke Verzerrung durch einstellige Zahlen gestoßen: Mit nur einer einstelligen unverdreht: 21s, mit 4 einstelligen unverdreht 16s, mit mehrfach technischen Verzögerungen ohne einstellige verdreht: 36s, ohne Probleme ohne einstellige verdreht: 26s.
Wirklich vergleichbar sind nur die 21s und 26s, die 16s sind sehr geschönt. Entweder jeder Lauf enthält gleichviele einstellige Zahlen (rechnet man nicht unbedingt mit und macht es interessanter) oder man lässt sie komplett heraus (Konzentration auf das Thema). Bei der Einstellung Zwanzigeins (ich nehme an, dass dort nach englischem Vorbild erst ab 20 unverdreht gesprochen wird) müsste man auch die Anzahl Zahlen im Bereich 11-19 betrachten.

**Comment by lglowania** [comment]
Danke für den Impuls, aber die geschilderte Problematik ist für mich schwer nachvollziehbar. 
Hilfreich wäre eine Schritt-für-Schritt-Anleitung zur Reproduktion des Problems oder ein Screencast.

**Comment by morfep78** [comment]
Ich verstehe den m.E. sehr sinnvollen Hinweis von dStephH wie folgt: Es sollten bei jeder Aufgabenstellung immer dieselbe Anzahl an einstelligen Zahlen vorkommen, also immer dieselbe Anzahl an Zahlen zwischen 0 bis 9. Begründung: diese einstelligen Zahlen haben nichts mit der eigentlichen Fragestellung zu tun, da sie in verdrehter und unverdrehter Sprechweise identisch gesprochen werden. Zudem sind die einstelligen Zahlen sehr einfach zu schreiben, einfacher als zweistellige. Sind nun die Anzahlen einstelliger Zahlen bei den verschiedenen Aufgaben unterschiedlich, d.h. treten durch die zufällige Zahlenauswahl z.B. bei 10 Aufgaben zu "zehneins" 2 einstellige Zahl auf, aber bei 10 Aufgaben zu "traditionell unverdreht" 5 einstellige Zahlen, so sind die Ergebnisse (Zeitdauern) nicht vergleichbar (verzerrt), wenn man damit die Auswirkung der Sprechweise messen will, denn die 3 zusätzlichen einstelligen Zahlen machen die 10 Aufgaben "traditionell unverdreht" leichter als die 10 Aufgaben "zehneins". Die einfachste Lösungsmöglichkeit ist es natürlich, einstellige Zahlen komplett aus allen Aufgabenstellungen herauszunehmen (damit ist die Anzahl einheitlich = 0 gesetzt, und das Problem gibt es nicht mehr). 

Jetzt kommt aber die sinnvolle Zusatzanmerkung von dStephH, dass dies zwar den Fall löst, wenn man z.B. die Sprechweise "zehneins" und "traditionell verdreht" vergleichen will, aber noch nicht komplett das Problem löst, wenn man "zwanzigeins" mit "traditionell verdreht" gegenüberstellen will. Denn in diesen beiden Sprechweisen werden nicht nur die Zahlen zwischen 0 und 9 sondern auch die Zahlen zwischen 10 und 19 identisch gesprochen. Die Zahlen zwischen 10 und 19 tragen also in diesem Vergleich auch nichts dazu bei, den Unterschied von "zwanzigeins" und "traditionell verdreht" zu messen. Es wäre somit z.B. eine Lösung in dem Vergleich "zwanzigeins" und "traditionell verdreht" die Zahlen 0 bis 19 auszusparen (nicht nur die Zahlen 0 bis 9). 

Diese einfache Lösung des Problems, nämlich irrelevante Zahlen (0 bis 9 bzw. 0 bis 19) aus den jeweiligen Aufgabenstellungen herauszunehmen, ergibt sich aus einer Lösung zu dem issue 3 (Zahlbereich bei “Hören & Schreiben“ #3). Denn dann kann jede Person den Zahlenbereich vorab so einstellen, dass ihr die Vergleiche unverzerrt erscheinen. Unter "Hilfe" oder einem anderen Punkt könnte dies Problem des sinnvollen Zahlbereichs für die Vergleiche von uns erläutert werden. 

Aber mir scheint es unabhängig von dieser Einstellmöglichkeit sinnvoll, immer und für alle Aufgaben den Zahlenbereich unterhalb von 10 bei "Hören & Schreiben" wegzulassen. Die Zahl 10 sollte also für alle Aufgabenstellungen in "Hören & Schreiben" auch das Minimum darstellen, das man einstellen kann.

**Comment by morfep78** [comment]
Dies Issue kann geschlossen werden, da nun ein Zahlbereich ausgewählt werden kann.
