### ISSUE TITLE
Level für den Kopfrechen-Trainer

### ISSUE THREAD

**Issue by lglowania** [zwanzigeins/zwanzigeins-app#28]
Für die Messung des Übungs-Fortschritts und einen "Produktivitäts-Vergleich" zwischen verdrehter und unverdrehter Sprechweise sind Level mit definierten Schwierigkeitsgraden erforderlich. 

Dabei könnte es vordefinierte Level geben und definierbare Level.
Die Definition eines Levels benötigt für alle 4 Operatoren (+,-,*,/) den Von-Bis-Bereich der ersten Zahl und den Von-Bis-Bereich der zweiten Zahl und die Anzahl zu stellenden Aufgaben (10, 20 oder 30).

Vordefinierte Level haben den Vorteil, dass sie den Nutzer der App sofort _spielen_ lassen und nicht, wie vermutlich aktuell, durch viele Optionen abschrecken.

Vordefinierte Level könnten sein:

- Addition 
  - einfach (2 bis 20 + 2 bis 20)
  - mittel (11 bis 100 + 11 bis 100)
  - schwer (11 bis 500 + 11 bis 500)

- Subtraktion (immer größer minus kleiner)
  - einfach (2 bis 20 - 2 bis 20)
  - mittel (11 bis 100 - 11 bis 100)
  - schwer (11 bis 500 - 11 bis 500)

- Multiplikation 
  - einfach (2 bis 5 + 2 bis 5)
  - mittel (2 bis 9 + 2 bis 9)
  - schwer (5 bis 20 + 5 bis 20)
  - Reihen des 1x1 für die Grundschule, also z.B. 5er-Reihe => 5 * 1 bis 9
  
- Division
  - einfach (10 bis 30 / 2 bis 5)
  - mittel (10 bis 100 / 2 bis 10)
  - schwer (100 bis 1000 / 2 bis 20)
  - Umkehraufgaben für Reihen des 1x1 für die Grundschule, also z.B. 5er-Reihe => 5 bis 50 / 5

- Addition/Subtraktion kombiniert in jeweiliger Schwierigkeitsstufe
- Multiplikation/Division kombiniert kombiniert in jeweiliger Schwierigkeitsstufe
- Addition/Subtraktion/Multiplikation/Division kombiniert kombiniert in jeweiliger Schwierigkeitsstufe

Zu jedem gespielten Level wird die benötigte Zeit und die Anzahl der fehlerhaften Eingaben gespeichert. Jede fehlerhafte Eingabe ergibt bei der Bewertung einen Malus von 3 Sekunden. Der Übungserfolg zu einem jeweiligen Level kann in einem Diagramm mit Spielzeitpunkt auf der x-Achse und Trainingserfolg (also benötigte Zeit mit Malus) auf der y-Achse eingesehen werden.

**Comment by morfep78** [comment]
4. Bulletpoint bei "Multiplikation": das kleine 1X1 führt aber nur zu Aufgaben mit 1stelligen Zahlen.  Ist dies für uns dennoch wichtig?

**Comment by morfep78** [comment]
Die obigen Vorschläge zur Definition von Levels sowie zu Ergebnisanzeigen und -speicherungen sind gut und sollten in ähnlicher Weise auch für den Bereich "Hören & Schreiben" entwickelt werden.

**Comment by morfep78** [comment]
Erledigt
