### ISSUE TITLE
Rechtliche Hinweise

### ISSUE THREAD

**Issue by lglowania** [zwanzigeins/zwanzigeins-app#29]
Da die Speicherung des Spielerfolgs auf dem Gerät des Benutzers mithilfe der LocalStorage-Technologie gespeichert wird, ist laut meinem Wissensstand zumindest hierfür ein rechtlicher Hinweis erforderlich. Eventuell könnten auch Hinweise zum Datenschutz benötigt werden.

**Comment by morfep78** [comment]
Dies sollte abgeglichen werden mit den üblichen juristischen Bedingungen, die gelten, wenn Apps aus einem App-Store heruntergeladen werden. Vielleicht wäre für uns bereits eine ausreichende rechtliche Sicherheit gegeben, wenn die App über Stores verbreitet wird, da der User damit gewisse Einwilligungen "automatisch" vornimmt.

**Comment by morfep78** [comment]
erledigt
