### ISSUE TITLE
Zahlbereich bei “Hören & Schreiben“

### ISSUE THREAD

**Issue by morfep78** [zwanzigeins/zwanzigeins-app#3]
Einstellungen erweitern: bei “Hören & Schreiben“ auch die Wahlmöglichkeit eines Zahlbereiches anbieten, wie beim Kopfrechnen. Wenn möglich auch mit Zahlen > 100.

**Comment by MarinaFromme** [comment]
Hierzu wäre mir wichtig, dass die App auf den Kindertablets durch eine Lehrerapp eingestellt werden sollte, sodass sich starke Rechner nicht ausruhen und schwache Rechner sich nicht direkt überfordern.

**Comment by morfep78** [comment]
Unser Mitglied Tim Böttcher kommentierte am 13.02.2022 zu "Hören und Schreiben": "Was mir jedoch noch fehlen würde, wäre das Üben von Zahlen im hunderter und tausender (+) Bereich. Dazu ergänzt sich dann natürlich auch das Rechnen mit entsprechenden Zahlen."

**Comment by morfep78** [comment]
Die Zahlenbereichsauswahl wurde hinzugefügt
