### ISSUE TITLE
Ergebnis kurz grün anzeigen ( 0.5s)

### ISSUE THREAD

**Issue by lglowania** [zwanzigeins/zwanzigeins-app#31]

**Comment by tbruckmaier** [comment]
hallo

**Comment by tbruckmaier** [comment]
Ein Vorschlag noch von mir:

Angenommen das korrekte Resultat ist "268". Wenn ich jetzt "3" eingebe, wird die Antwort sofort rot markiert (da die richtige Anwort ja mit "2" anfängt). Wenn ich eine halbe Sekunde warte, wird bei der nächsten Eingabe die Antwort gelöscht (also z.B. Eingabe "3", halbe Sekunde warten, Eingabe "4" -> im Feld steht einfach nur "4"). Wenn ich aber schnell tippe, kann ich eine beliebig lange (falsche) Antwort eintippen.
Wenn ich zuerst "2" eingebe (also den ersten Teil der richtigen Antwort), kann ich auch länger warten, und dann erst die nächste Ziffer eingeben (korrekterweise wird dann die Eingabe nicht vorher gelöscht)

Ist das Absicht, dass ich bereits bei der ersten Ziffer Rückmeldung bekomme, ob das Erbenis richtig wird?
Und ebenso Absicht, dass die Eingabe in manchen Fällen automatisch gelöscht wird, aber in manchen nicht?

Ich würde ja vorschlagen (ohne jetzt die bisherige Motivation zu kennen):
das Antwortfeld bleibt grauschwarz-neutral, bis ich manuell auf einen neuen Button "Prüfen" / "Absenden" / .. klicke, erst dann verfärbt sich das Feld rot oder grün. Wenn die Antwort rot ist, wird vor der nächsten Eingabe das Feld geleert, wenn grün, wird automatisch die nächste Frage angezeigt.

**Comment by morfep78** [comment]
Ich finde diesen Vorschlag gut, denn er vermeidet offensichtliche Probleme:

„Ich würde ja vorschlagen (ohne jetzt die bisherige Motivation zu kennen):
das Antwortfeld bleibt grauschwarz-neutral, bis ich manuell auf einen neuen Button "Prüfen" / "Absenden" / .. klicke, erst dann verfärbt sich das Feld rot oder grün. Wenn die Antwort rot ist, wird vor der nächsten Eingabe das Feld geleert, wenn grün, wird automatisch die nächste Frage angezeigt.“

Lukas wollte m.E. umsetzen, dass man eine Eingabe möglichst schnell durchführen kann, also ohne einen zusätzlichen Abschickbutton benutzen zu müssen. Lukas, wie siehst du das? Hast du einen besseren Vorschlag, der die von Thomas benannten Probleme vermeidet, aber ohne dass man einen weiteren Button drücken muss?

LG
Peter 

 

Von: tbruckmaier ***@***.***> 
Gesendet: Sonntag, 3. April 2022 18:11
An: zwanzigeins/zwanzigeins-app ***@***.***>
Cc: morfep78 ***@***.***>; Comment ***@***.***>
Betreff: Re: [zwanzigeins/zwanzigeins-app] Ergebnis kurz grün anzeigen ( 0.5s) (Issue #31)

 

Ein Vorschlag noch von mir:

Angenommen das korrekte Resultat ist "268". Wenn ich jetzt "3" eingebe, wird die Antwort sofort rot markiert (da die richtige Anwort ja mit "2" anfängt). Wenn ich eine halbe Sekunde warte, wird bei der nächsten Eingabe die Antwort gelöscht (also z.B. Eingabe "3", halbe Sekunde warten, Eingabe "4" -> im Feld steht einfach nur "4"). Wenn ich aber schnell tippe, kann ich eine beliebig lange (falsche) Antwort eintippen.
Wenn ich zuerst "2" eingebe (also den ersten Teil der richtigen Antwort), kann ich auch länger warten, und dann erst die nächste Ziffer eingeben (korrekterweise wird dann die Eingabe nicht vorher gelöscht)

Ist das Absicht, dass ich bereits bei der ersten Ziffer Rückmeldung bekomme, ob das Erbenis richtig wird?
Und ebenso Absicht, dass die Eingabe in manchen Fällen automatisch gelöscht wird, aber in manchen nicht?

Ich würde ja vorschlagen (ohne jetzt die bisherige Motivation zu kennen):
das Antwortfeld bleibt grauschwarz-neutral, bis ich manuell auf einen neuen Button "Prüfen" / "Absenden" / .. klicke, erst dann verfärbt sich das Feld rot oder grün. Wenn die Antwort rot ist, wird vor der nächsten Eingabe das Feld geleert, wenn grün, wird automatisch die nächste Frage angezeigt.

**Comment by lglowania** [comment]
Das Verhalten mit dem automatischen Löschen der falschen Antwort nach 0.5s ist inspiriert von der Android-App *Math Workout*. https://play.google.com/store/apps/details?id=io.ts.mathworkout&hl=de&gl=US. Wobei ich diese vor ca. 10 Jahren benutzt hatte.

Ich habe die App *Math Workout* und auch die *Zwanzigeins-App* bereits relativ viel gespielt und bin überzeugt, dass ein Abschicken-Button den Flow und den Spiel-Spaß recht stark stören würde. Wenn ihr das aber drin haben wollt, so würde ich vorschlagen das zunächst experimentell durch ein URL-Parameter aktivierbar zu machen, so dass wir diesen Ansatz ausprobieren könnten. Also z.B. würde es mit so:
```
https://zwanzigeins.jetzt/app?experimental=submit-answer-button-enabled
```

**Comment by morfep78** [comment]
Hallo zusammen,ich habe die aktuelle Version mit der Anzeige in grün und rot ausprobiert. Danke für diese Programmierung! Ich finde das sehr gut.Thomas, selbst wenn du schnell beliebige Ziffern tippst, bleibt die Anzeige rot, was doch korrekt ist Übersehe ich etwas? Warum denkst du, dass ein Eingabebutton zusätzlich erforderlich ist? Übersehe ich etwas?LGPeter sent from my mobileVon: tbruckmaier ***@***.***>Gesendet: Sonntag, 3. April 2022, 18:11An: zwanzigeins/zwanzigeins-app ***@***.***>Cc: morfep78 ***@***.***>; Comment ***@***.***>Betreff: Re: [zwanzigeins/zwanzigeins-app] Ergebnis kurz grün anzeigen ( 0.5s) (Issue #31)

Ein Vorschlag noch von mir:

Angenommen das korrekte Resultat ist "268". Wenn ich jetzt "3" eingebe, wird die Antwort sofort rot markiert (da die richtige Anwort ja mit "2" anfängt). Wenn ich eine halbe Sekunde warte, wird bei der nächsten Eingabe die Antwort gelöscht (also z.B. Eingabe "3", halbe Sekunde warten, Eingabe "4" -> im Feld steht einfach nur "4").. Wenn ich aber schnell tippe, kann ich eine beliebig lange (falsche) Antwort eintippen.

Wenn ich zuerst "2" eingebe (also den ersten Teil der richtigen Antwort), kann ich auch länger warten, und dann erst die nächste Ziffer eingeben (korrekterweise wird dann die Eingabe nicht vorher gelöscht)

Ist das Absicht, dass ich bereits bei der ersten Ziffer Rückmeldung bekomme, ob das Erbenis richtig wird?

Und ebenso Absicht, dass die Eingabe in manchen Fällen automatisch gelöscht wird, aber in manchen nicht?

Ich würde ja vorschlagen (ohne jetzt die bisherige Motivation zu kennen):

das Antwortfeld bleibt grauschwarz-neutral, bis ich manuell auf einen neuen Button "Prüfen" / "Absenden" / .. klicke, erst dann verfärbt sich das Feld rot oder grün. Wenn die Antwort rot ist, wird vor der nächsten Eingabe das Feld geleert, wenn grün, wird automatisch die nächste Frage angezeigt.

**Comment by morfep78** [comment]
Hallo zusammen,wie ich schon schrieb: ich sehe ohne Abschickbutton bei der jetzigen Version keine Probleme. Sorry, wenn ich mit meiner ersten Antwort auf Thomas Frage verwirrt habe. Vielleicht übersehe ich aber auch etwas, was Thomas als Schwierigkeit erkannt hat.LGPeter sent from my mobileVon: Lukas Glowania ***@***.***>Gesendet: Montag, 4. April 2022, 10:59An: zwanzigeins/zwanzigeins-app ***@***.***>Cc: morfep78 ***@***.***>; Comment ***@***.***>Betreff: Re: [zwanzigeins/zwanzigeins-app] Ergebnis kurz grün anzeigen ( 0.5s) (Issue #31)

Das Verhalten mit dem automatischen Löschen der falschen Antwort nach 0.5s ist inspiriert von der Android-App Math Workout. https://play.google..com/store/apps/details?id=io.ts.mathworkout&hl=de&gl=US. Wobei ich diese vor ca. 10 Jahren benutzt hatte.

Ich habe die App Math Workout und auch die Zwanzigeins-App bereits relativ viel gespielt und bin überzeugt, dass ein Abschicken-Button den Flow und den Spiel-Spaß recht stark stören würde. Wenn ihr das aber drin haben wollt, so würde ich vorschlagen das zunächst experimentell durch ein URL-Parameter aktivierbar zu machen, so dass wir diesen Ansatz ausprobieren könnten. Also z.B würde es mit so:

https://zwanzigeins.jetzt/app?experimental=submit-answer-button-enabled

**Comment by tbruckmaier** [comment]
Hi, ne für mich passt alles, war nur vom Code verwirrt, aber der Spielflow ist in dieser Variante natürlich flüssiger. Und da es ja bei dem Spiel ja auch nicht darum geht richtige Antworten abzuprüfen, ist das bestimmt besser so.

**Comment by lglowania** [comment]
Ok, das Issue ist umgesetzt und ich schließe es. Bei Interesse den Vorschlag in einem neuen Issue öffnen. Vielen Dank!
