### ISSUE TITLE
Wording: 'Sie' oder 'Du'?

### ISSUE THREAD

**Issue by lglowania** [zwanzigeins/zwanzigeins-app#39]
Im weiteren Verlauf sollen bei den 'Spielen' im Vorfeld kleine Hilfe/Beschreibungstexte eingebracht werden. Vermutlich wirkt eine persönliche Ansprache des Benutzers am besten, nach dem Motto: *Tippe auf den Button um ....*. Ich würde favorisieren hier die Du-Ansprache zu verwenden.

**Comment by morfep78** [comment]
Die Du-Ansprache erscheint mir sinnvoller, da auch Kinder angesprochen werden sollen. Und Erwachsene werden üblicherweise in Erläuterungstexten zu vielen anderen Apps und Anwendungen geduzt, so dass m.E. keine Ablehnung der App durch Erwachsene allein durch das Duzen zu erwarten ist.

**Comment by lglowania** [comment]
Ok, das ist dann geklärt und wir setzen das überall so um.

**Comment by morfep78** [comment]
Ok

Peter

 

Von: Lukas Glowania ***@***.***> 
Gesendet: Dienstag, 5. April 2022 10:18
An: zwanzigeins/zwanzigeins-app ***@***.***>
Cc: morfep78 ***@***.***>; Comment ***@***.***>
Betreff: Re: [zwanzigeins/zwanzigeins-app] Wording: 'Sie' oder 'Du'? (Issue #39)

 

Ok, das ist dann geklärt und wir setzen das überall so um.
