### ISSUE TITLE
Division ganzzahlig

### ISSUE THREAD

**Issue by morfep78** [zwanzigeins/zwanzigeins-app#4]
Bei “Division“ die Aufgaben auf solche mit ganzzahligen Ergebnissen beschränken, z.B. so: zufällig gezogene Aufgabe a/b verwerfen, wenn abs((a/b)-int(a/b))>=0.0001 und dann neue Aufgabe ziehen bis abs((a/b)-int(a/b))<0.0001; abs ist Absolutbetrag, int ist Integerfunktion, d.h. größte ganze kleiner oder gleich a/b. Ich hoffe, das hat die Programmiersprache, mit der du arbeitest.

**Comment by lglowania** [comment]
Ist eingebracht. JavaScript hat keine int()-Funktion, aber man kann leicht herausfinden ob eine Division zu einem Restbetrag führte oder nicht. 

Divisions-Aufgaben, wo eine Zahl durch sich selbst geteilt wird, oder Divisionen durch 1 werden nicht gestellt, da uninteressant.
