### ISSUE TITLE
Einleitungstext für 'Hören und Schreiben'

### ISSUE THREAD

**Issue by lglowania** [zwanzigeins/zwanzigeins-app#40]
Derzeit ist der Einleitungstext:

```Hier soll ein 'Spiel-Modus' entstehen, bei dem eine gesprochene Zahl korrekt eingegeben werden muss.```

Sollte man inhaltlich ändern für mehr Hilfe-Charakter.

**Comment by morfep78** [comment]
Vorschlag:

Pro Aufgabe wird dir eine Zahl vorgesprochen, die du dann korrekt und schnell eintippen sollst. 
Die Anzahl der Aufgaben kannst du hier vorwählen, auch den Bereich aus dem die vorgesprochenen Zahlen stammen sollen. Am Ende wird dir die Zeitdauer angezeigt, die du zum Lösen der Aufgaben benötigt hat.
Unter „Einstellungen“ kannst du die Sprechweise einstellen, in der dir die Zahlen vorgesprochen werden, z.B. „zehneins“ (d.h. ab 11 unverdreht vorlesen lassen) oder „traditionell verdreht“. Auch die Sprechgeschwindigkeit kannst du dort wählen oder die Darstellung (z.B. heller oder dunkler Hintergrund). 
Du kannst mit „Hören & Schreiben“ erproben, wann du Zahlen besser eingeben kannst: wenn sie dir in stellenwertgerechter Sprechweise oder in der üblichen verdrehten Sprechweise vorgelesen werden. Du wirst erstaunt sein, wie leicht es geht, wenn die Zahlen unverdreht vorgesprochen werden.

**Comment by morfep78** [comment]
entfällt, da ein Handbuch verfasst wird
