### ISSUE TITLE
Ziehen von Zufallszahlen für Division unter Umständen fehlerhaft

### ISSUE THREAD

**Issue by lglowania** [zwanzigeins/zwanzigeins-app#41]

**Comment by morfep78** [comment]
Lösungsvorschlag: „rückwärts“ über Multiplikation rechnen, d.h.

1) Zufälliges Ziehen des Ergebnisses, z.B. 12
2) Zufälliges Ziehen des Divisors (= Nenner), z.B. 23
3) Berechnen des Dividenden (= Zähler), also 12*23 = 276
4) Aufgabe stellen: 276 : 23

**Comment by morfep78** [comment]
Lösungsvorschlag für Problem bei der Division

Levels der Division für Dividend (Zähler) / Divisor (Nenner):
•	einfach (10 bis 30 / 2 bis 5)
•	mittel (10 bis 100 / 2 bis 10)
•	schwer (100 bis 1000 / 2 bis 20)

bisheriger Ansatz: Divisionsaufgabe „rückwärts“ über Multiplikation bestimmen, d.h.
1) Zufälliges Ziehen des Ergebnisses, z.B. 12
2) Zufälliges Ziehen des Divisors (= Nenner), z.B. 23
3) Berechnen des Dividenden (= Zähler), also 12*23 = 276
4) Aufgabe stellen: 276 : 23

Problem: Ziehen der beiden Zufallszahlen muss geeignet eingegrenzt werden, um die vorgegebenen Levelbereiche einzuhalten. 


Lösungsvorschlag:
Bei vorgegebenem Level (xz bis yz / xn bis yn):
1) Nenner n zwischen xn bis yn zufällig ziehen
2) Ergebnis e zwischen 1+int(xz/n-0.001) und int(yz /n) zufällig ziehen. 
Hier bedeutet int(x) die Integerfunktion, d.h. die größte ganze Zahl kleiner oder gleich x. Also z.B. int(8.7)=8, int(7/2) = int(3.5) =3, int(8/4) = int(2) = 2, int(8/4-0.001) = int(1.999) = 1.
3) Berechnen Dividend: z = n*e
4) Aufgabe stellen: z/n
Dadurch wird immer die Levelbedingung stets eingehalten. Anmerkung: Der Term -0.001 ist groß genug, um immer vom Programm korrekt bedient zu werden, aber klein genug, um alle Bruchstücke zu unterschreiten, die bei den Divisionen aller hier möglichen Zahlen auftreten können.


Beispiel 1:
Level einfach (10 bis 30 / 2 bis 5), d.h. xz = 10, yz = 30,  xn = 2, yn = 5
1) Nenner zwischen xn = 2 bis yn = 5 zufällig ziehen, z.B. n = 3
2) Ergebnis zwischen 1+int(10/3-0.001) = 1+int (3.334333…) = 1+3 = 4 und int(30/3) = int(10) = 10 zufällig ziehen, z.B. e = 5
3) Berechnen Zähler: z = 5*3 = 15
4) Aufgabe stellen: 15/3

Beispiel 2:
Level einfach (10 bis 30 / 2 bis 5), d.h. xz = 10, yz = 30,  xn = 2, yn = 5
1) Nenner zwischen xn = 2 bis yn = 5 zufällig ziehen, z.B. n = 5
2) Ergebnis zwischen 1+int(10/5-0.001) = 1+int(1.999) = 1+1 = 2 und int(30/5) = int(6) = 6 zufällig ziehen, z.B. e= 4
3) Berechnen Dividend: z = 5*4 = 20
4) Aufgabe stellen: 20/5

Beispiel 3:
Level einfach (10 bis 30 / 2 bis 5), d.h. xz = 10, yz = 30,  xn = 2, yn = 5
1) Nenner zwischen xn = 2 bis yn = 5 zufällig ziehen, z.B. n = 4
2) Ergebnis zwischen 1+int(10/4-0.001) = 1+int(2.499) = 1+2 = 3 und int(30/4) = int(7.5) = 7 zufällig ziehen, z.B. e = 7
3) Berechnen Dividend: z = 4*7 = 28
4) Aufgabe stellen: 28/4
