### ISSUE TITLE
Zahlbereich für "Hören & Schreiben" ab 10000 fehlerhaft

### ISSUE THREAD

**Issue by morfep78** [zwanzigeins/zwanzigeins-app#43]
Wird die Anfangszahl auf 10000 oder höher gesetzt, kommt eine unklare Zahlenansage, in der das Teilwort "undef" vorkommt.

**Comment by lglowania** [comment]
Wir sollten die Obergrenze für stellenwertgerechte Aussprache auf maximal 999 Milliarden ermöglichen. Der Algorithmus für die Herstellung der unverdrehten Sprachsequenz muss erweitert werden.

**Comment by morfep78** [comment]
OK!

 

Von: Lukas Glowania ***@***.***> 
Gesendet: Dienstag, 5. April 2022 10:24
An: zwanzigeins/zwanzigeins-app ***@***.***>
Cc: morfep78 ***@***.***>; Author ***@***.***>
Betreff: Re: [zwanzigeins/zwanzigeins-app] Zahlbereich für "Hören & Schreiben" ab 10000 fehlerhaft (Issue #43)

 

Wir sollten die Obergrenze für stellenwertgerechte Aussprache auf maximal 999 Milliarden ermöglichen. Der Algorithmus für die Herstellung der unverdrehten Sprachsequenz muss erweitert werden.
