### ISSUE TITLE
Zwanzigeinsapp in App-Stores anbieten

### ISSUE THREAD

**Issue by morfep78** [zwanzigeins/zwanzigeins-app#44]
Die Mehrzahl der Anwender "aktiviert" Apps durch Herunterladen aus dem jeweiligen App-Store. Vielen Anwendern ist das Abrufen einer App von einer anderen Website fremd oder gar verdächtig. Deshalb sollte auch die Zwanzigeins-App in den App-Stores für Android- und Apple-Smartphones angeboten werden.

**Comment by lkwr** [comment]
Das bereitstellen von einer PWA ist leider nur im Google Play Store möglich. Der Apple App Store bietet das aktuell soweit ich weiß leider nicht an.

**Comment by morfep78** [comment]
Wir bleiben bei unserem ausschließlichen Angebot über die Zwanzigeins-Website. Änderungen an der App können wir so viel leichter umsetzen. Wir sind so auch unabhängig von Bedingungen des Google Play Stores
