### ISSUE TITLE
Formatierung mit Prettier

### ISSUE THREAD

**Issue by lkwr** [zwanzigeins/zwanzigeins-app#50]
Für die Leserlichkeit und Sauberkeit des Codes, fände ich es sinnvoll den Codeformatierer Prettier zu verwenden.

Aktuell werden, soweit ich das auf dem Smartphone richtig erkenne, Tabulatoren im Code verwendet, diese würden durch Prettier in besser lesbare Leerzeichen umgewandelt werden.

Allgemein sorgt Prettier für einen Qualitativeren und Einheitlicheren Code.

Oder was hält ihr von dem Vorschlag? Kann bei Gelegenheit gern ein PR dazu machen.

**Comment by lglowania** [comment]
Ich benutze Eclipse als IDE und da kann ich Prettier nicht so einfach integrieren, scheint mir. Bei Eclipse kann ich auch das Auto-Formatting für JavaScript derzeit nicht vernünftig konfigurieren. Mein Auto-Formatter macht also Tabs. Ich verstehe nicht, was an Leerzeichen besser lesbar ist, sonst würde ich mich gerne irgendwie um die Leerzeichen bemühen.

Ich habe jetzt alles einmal auto-formattiert für die Einheitlichkeit. Bei dem geringen Code-Umfang seh ich kaum Mehrwert in diesem Extra-Tool und den Nachteil, dass es mit meiner IDE nicht gut zusammenspielt. Bei Zeiten wäre ich eher dafür eslint einzubringen.
