### ISSUE TITLE
verdrehte Sprechweise

### ISSUE THREAD

**Issue by morfep78** [zwanzigeins/zwanzigeins-app#6]
Einstellungen: Optional soll auch die verdrehte Sprechweise angeboten werden (dann kann man Unterschiede in der Schnelligkeit z.B. beim "Hören & Schreiben" austesten. Dies erscheint mir sehr wichtig, um für die unverdrehte Sprechweise mit den Spielaufgaben eingängig werden zu können. Auch für die Lehrerin, Frau Fromme, die nach einer solchen App fragte, war diese Option wesentlich.

**Comment by MarinaFromme** [comment]
Da bin ich nun. Richtig, ich fände es auch gut, wenn die Kinder selbst wählen könnten welche der beiden Sprechweisen sie zur Bearbeitung der Aufgaben bevorzugen.

**Comment by lglowania** [comment]
Man kann jetzt aus den Sprechweisen *zehneins*, *zwanzigeins* und *traditionell verdreht* in den Einstellungen wählen.
