### ISSUE TITLE
"Sofortige" Installation eines Updates der App

### ISSUE THREAD

**Issue by morfep78** [zwanzigeins/zwanzigeins-app#66]
Die App installiert sich „leise“, d.h. dass man muss nach dem Runterladen einer neuen Version die App öffnen, schließen und wieder öffnen, damit die Installation erfolgt. Dies sollte so geändert werden, dass die Installation automatisch nach dem Herunterladen abgeschlossen wird.

**Comment by lglowania** [comment]
Das wurde jetzt mit #60 behandelt: Wenn ein Update installiert wurde, wird ein Button angezeigt, der zum Neu-Laden der App auffordert. Theoretisch könnte man auch das Neu-Laden automatisch machen. Aber evt. würde sich der Benutzer wundern, warum die App kurz neu lädt. Außerdem weißt man den Nutzer so auf ein Update hin. Klären wir noch im Meeting.
